_wandb:
    value:
        cli_version: 0.25.0
        e:
            i9u4tm4dpn9fg1aj0axgxbup6n4c8yjw:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                args:
                    - --model_config
                    - configs/mamba_tinystories_1M/model.yaml
                    - --tokenizer_config
                    - configs/mamba_tinystories_1M/tokenizer.yaml
                    - --checkpoint
                    - results/mamba_tinystories_1M/mamba_best.pt
                    - --num_workers
                    - "0"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "435352584192"
                email: kosar.hazrati@gmail.com
                executable: /Users/kosaralehosseini/anaconda3/bin/python
                git:
                    commit: 03a41820366194169fb7f11d79c0b60880ad9ed9
                    remote: https://github.com/KosarHazrati/pocket-narrator.git
                host: MacBook-Pro-von-Kosar.local
                memory:
                    total: "17179869184"
                os: macOS-15.3.1-arm64-arm-64bit
                program: -m pocket_narrator.models.mamba.mamba_evaluation
                python: CPython 3.11.5
                root: /Users/kosaralehosseini/Documents/pocket-narrator/pocket_narrator/models/mamba/pocket-narrator
                startedAt: "2026-02-24T06:03:02.551109Z"
                writerId: i9u4tm4dpn9fg1aj0axgxbup6n4c8yjw
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.5
            "5": 0.25.0
            "6": 4.57.5
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 1
bertscore_model:
    value: null
checkpoint:
    value: results/mamba_tinystories_1M/mamba_best.pt
d_conv:
    value: 3
d_model:
    value: 64
d_state:
    value: 16
dropout:
    value: 0
enable_ref_metrics:
    value: false
expand:
    value: 2
lm_dataset_dir:
    value: ./lm_dataset/tinystories_1M
max_new_tokens:
    value: 64
mode:
    value: evaluation
n_layers:
    value: 8
num_params:
    value: 1498752
seq_len:
    value: 256
temperature:
    value: 0.8
top_k:
    value: null
vocab_size:
    value: 10000
